###
POST http://localhost:3005/api/consecutivo HTTP/1.1
Content-Type: application/json

      { "codigo": "BG", "descripcion": "Bebidas Gaseosas" }

###
GET http://localhost:3005/api/consecutivo HTTP/1.1


###
GET http://localhost:3005/api/consecutivo/626ad3e59e74faee6fad8fac HTTP/1.1

###
PUt http://localhost:3005/api/consecutivo/62187fe073acc208b2acf78c HTTP/1.1
Content-Type: application/json

{
    "name": "Darla",
    "age": "21",
    "email": "darla@gmail.com"
}

###
DELETE  http://localhost:3005/api/consecutivo/626ad471da99134029676287 HTTP/1.1
